### ISSUE TITLE
Joblib

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpo#226]
Placeholder issue for integrating joblib. This has two major facets:

 1. Automatically caching function output such as AAM building
 2. Allowing ``parfor``-like semantics. This is an important requirement for running experiments.

**Comment by patricksnape** [comment]
This is unlikely ever to get in - mostly due to the fact that joblib doesn't play very nicely when it is nested inside a class structure. It works much better when you are doing some large job at the root of a notebook for example. Also, joblib just wraps pickle which is terrible at dealing with partial functions and lambdas - which we now use quite a lot.

**Comment by jabooth** [comment]
@patricksnape yeah it's a shame this, especially as we are actually getting bitten quite hard by been single threaded when building large models. when so much of it (image loading, preparing, feature extraction namely) is inherently parallelizable. Wonder if there is a way to achieve this using multiprocess directly?

**Comment by jabooth** [comment]
@patricksnape have we ever explored `pathos.multiprocessing`? Mentioned in this blog post:

http://matthewrocklin.com/blog/work/2013/12/05/Parallelism-and-Serialization/

**Comment by patricksnape** [comment]
Yeah it uses dill underneath (since those guys make dill as well). But
there are more issues than just dill (though that is a big issue) around
multiprocessing and threading within BLAS libraries. In general it is a bit
of a mess any may be more effort than it is worth at the moment. I feel
like you are going to end up re-implementing joblib...

**Comment by jabooth** [comment]
OK, fair enough. For future reference although it's a little hard to find, there is a standalone up-to-date version of the dill fork of mutliprocessing here: https://pypi.python.org/pypi/multiprocess
