### ISSUE TITLE
Face and Object Detection

### ISSUE THREAD

**Issue by jalabort** [menpo/menpo#270]
`Face detection` and `object detection` in general need to be available in `Menpo`. The steps to make this a reality are:
- [ ] check and compare the performance of `opencv`'s and `dlib`'s default face detector.
- [ ] asses how easy it is to retrain the previous detectors with our own data and if whether or not these methods will be able to generalize to other object categories (snails for example...).
- [ ] make the chosen approach accessible to the `Fitter/Fitting` framework.

**Comment by futurely** [comment]
Cheney et al. benchmarked OpenCV and Dlib face detection performance on the IJB-A and FDDB datesets [1].

[1] J. Cheney, B. Klein, A. K. Jain and B. F. Klare, "Unconstrained Face Detection: State of the Art Baseline and Challenges", ICB, Phuket, Thailand, May 19-22, 2015.

**Comment by patricksnape** [comment]
@futurely Thanks for that citation! We also found that dlib was a lot more performant in the end!
