### ISSUE TITLE
pip install menpo without having any Python deps

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#295]
Cyassimp and Cyrasterize both can pip install without first having Cython and Numpy installed. This is because we do some trickery in the setup.py to avoid importing Cython and numpy until after they have been downloaded as dependencies.

This same scheme is fairly trivial to bring to Menpo so that 

```
pip install menpo
```

will work so long as you have all the system libraries we require installed.

**Comment by jabooth** [comment]
@patricksnape can you confirm this is now working at least for OS X? I think this is basically OK now, we should probably just test all platforms before release and remember to push the update to PyPI.

**Comment by patricksnape** [comment]
Yes this worked for my on my laptop (OSX), but I haven't tested on any
other platform.

**Comment by patricksnape** [comment]
Also works on Linux (Ubuntu 14.04)
