### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#419]
### The case for Python 3
We have already done a fair amount of the groundwork working towards Python 3 compatibility (#399). As we currently only target Python 2.7+, and don't use strings as binary in many cases (if at all) we are pretty well positioned to get full Python 3 compatibility. Until now there hasn't been many cases where Python 3 would improve Menpo, but the list is starting to grow:

- `pathlib`is in the standard library - one less thing to install.
- A supported version of `virtualenv` (`pyvenv`) and `pip` is included. Opens up potential for easier installs (way down the line)
- Python 3.3 made it much easier to [introspect functions](https://docs.python.org/3/whatsnew/3.3.html#pep-362-function-signature-object). This is needed for robust serialisation of functions (for instance, needed to solidly serialize an AAM, etc)

Before the last item the list was fairly uninspiring, but the ability to solidly serialise out functions would make serialisation of any Menpo type much more solid.

Finally, as a modern project without any legacy constrains, we should enthusiastically look to the future of the Python language. Python 2 is never going to see any further enhancements - every year Python 3 because more powerful and capable.

### What's the downside?

Mayavi [does not support Python 3](https://github.com/enthought/mayavi/issues/84). We would have to consider how to handle this. Personally, I feel that Mayavi (or more fairly, it's major dependencies, VTK + GTK/QT) make Menpo feel 'flakey' at times. Whilst conda improves things, I still have the following in my `~/.zshrc` to make Mayavi work for me on Mavericks:
```bash
export QT_API=pyqt
export ETS_TOOLKIT=qt4
```
This kind of stuff does not install confidence when you are asking a student to install Menpo.

#### So how can we get away from Mayavi?

[Vispy](http://vispy.org/) is a young project that aims to provide a modern replacement for Mayavi that will work in the browser through IPython notebooks. It's feasible down the line that this could replace Mayavi in Menpo as the 3D visualisation package of choice.

We also have our own [3D annotation tool](www.landmarker.io) that I plan to adapt as an IPython notebook widget in the near future. The focus of the landmarker will always be much narrower than what Mayavi provides, but it does demonstrate that we can develop our own domain specific tools for visualization to replace our dependence on Mayavi.

#### How do we get to full Python 3 support?

[This guide](https://wiki.python.org/moin/PortingToPy3k/BilingualQuickRef) gives a lot of great recommendations that help make a codebase work with Python 2 and 3. We might also consider using [future](https://pypi.python.org/pypi/future) which is a compatibility layer. It allows us to write idiomatic Python 3 code, which will work on Python 2.7. At some point you could just remove the statements from the top of each file and you would be left with a clean Python 3 codebase.

- [ ] Use [futurize](http://python-future.org/futurize_cheatsheet.html) stage 0 to modernise Menpo without adding a dependency on future
- [x] Change our use of ABC's so we don't need to use metaclasses directly
- [ ] Move to new style classes implicitly (i.e. remove `object` superclass)
- [ ] Consider using futurize stage 2 to add a dependency on future, but have Python 3 support
- [x] Get all tests passing on Python 3
- [x] Binstar builds for Python 3
- [x] Have clean separation of Mayavi so trying to use it on Python 3 is well behaved
- [ ] Remove dependency on Mayavi with another solution

The last item on this list could take a long time to achieve. Still we can get all of the way up that point with relatively little work.

**Comment by patricksnape** [comment]
Partially addressed by #552.

**Comment by jabooth** [comment]
@patricksnape what is actually left on this? Or can we close (and add separate issues for menpofit, menpo3d, menpodetect?)

**Comment by patricksnape** [comment]
This is solved for menpo itself. The subprojects are all partially solved, but menpo3d will always involve some form of partial functionality on Python3 due to Mayavi.
