### ISSUE TITLE
Undesired behaviour of warp_to_mask in MaskedImage

### ISSUE THREAD

**Issue by jalabort** [menpo/menpo#449]
The method `warp_to_mask` in `MaskedImage` always warps the mask on the particular `MaskedImage` from which the method is executed. 

While this makes a lot of sense in general, it might cause problems when using `AAMs`. In particular, for some edge cases the `warped image` and the `reference frame` end up having different number of pixels which causes the AAM fitting to crash.

This can be easily solved by bringing back the old `kwarg` `warp_mask` but because `warp_to_mask` is a very general method I though I would open this issue for further discussion.

**Comment by jabooth** [comment]
@jalabort did you look into this? I think we just decided to raise a warning if using masked images in fitting. This will now be on menpofit, so once it's done over there we can close this issue.

**Comment by patricksnape** [comment]
This has changed now with the introduction of #563. Now, an explicit exception is raised (``OutOfMaskSampleError``) when you attempt to warp a masked image outside of it's mask. However, we still need to make sure that ``as_unmasked`` is called in Menpofit for AAMs.
