### ISSUE TITLE
additional widgets

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#456]
Following #452, is there any more widgets we think would be useful?

**Comment by nontas** [comment]
The pointcloud widget needs to be updated in the future in order to support landmarks rendering. This means that the landmark options tab needs to be added.

**Comment by jalabort** [comment]
It would be great to incorporate a `slider` under the tab `Landmarks` in the `visualize_images` widget so that one can slide across and see all landmarks from a given image in a fast way (instead of having to click every time on the drop down menu)

**Comment by patricksnape** [comment]
Additional widgets should be addressed over on github.com/menpo/menpowidgets
