### ISSUE TITLE
generalized histogram and binary patterns

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#459]

**Comment by sajjo79** [comment]
Hi, Have you got any code to generate generalized histogram of multiple images

**Comment by patricksnape** [comment]
I'm not sure what you mean? This issue was about some really old work we were doing on binning of features other than gradients which had different ranges.

**Comment by sajjo79** [comment]
http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6738468
Multiple histogram matching
Please refer to above given link, I want to calculate a generalized histogram of multiple images and then using that i want to find histogram matching for all candidate image.

**Comment by patricksnape** [comment]
No sorry, this issue was not about that method so we do not have any code for it

**Comment by patricksnape** [comment]
C++ code removed
