### ISSUE TITLE
Clean up inplace methods on image

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#482]
We have a few inplace methods where there really isn't any performance reason to have it on the image class. As we have changed so much API since 0.3.0 we should tidy this up now otherwise it's going to be baggage we have to maintain going forwards.

**Comment by patricksnape** [comment]
@jabooth is this done?

**Comment by patricksnape** [comment]
I think this is mostly done. Particularly for 0.6.0, I think we can close this then (or at least make sure it really is done and then close it).

**Comment by patricksnape** [comment]
This is still not done:

  - ``constrain_mask_to_landmarks``
  - ``constrain_landmarks_to_bounds``

**Comment by jabooth** [comment]
@patricksnape were these all addressed in #687?

**Comment by patricksnape** [comment]
Yes
