### ISSUE TITLE
LK builder and fitter with affine transform

### ISSUE THREAD

**Issue by nontas** [menpo/menpo#496]
We could consider adding the `LKBuilder` and `LKFitter` classes in the `fitmultilevel` package, following the same structure as in `ATMBuilder` and `ATMFitter`. This addition doesn't really make much sense because these nothing really to build; LK is just an image alignment algorithm. However, it will be easier for someone to use LK (rather than using it through the `fit` package) and apply it in a pyramidal multilevel manner.

**Comment by patricksnape** [comment]
This is an issue with MenpoFit and @jalabort is already solving this as we speak
