### ISSUE TITLE
.LJSON maps to PointGraph which is an incomplete representation

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#497]
Landmarker.io allows for graphs with isolated nodes, and so LJSON files permit this configuration. This is not allowed in PointGraph yet we try and turn any LJSON file into PointGraph, causing problems.

**Comment by jabooth** [comment]
note that this builds on #408. After discussions today with @patricksnape and @nontas decided that the ljson format should be updated to be full fidelity - that is any valid menpo landmark set can be saved to LJSON and interpreted by the landmarker.

**Comment by patricksnape** [comment]
So this is done now?

**Comment by jabooth** [comment]
As far as menpo is concerned yes- but landmarkerio is now waiting for menpo 0.4.0 before it can adopt LJSON v2

**Comment by jabooth** [comment]
This is now all resolved.
