### ISSUE TITLE
Documentation for 0.4.0 final

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpo#535]
Since I'm keen to do a 0.4.0 release before we pull in the channels and move to 0.5.0, the biggest blocker (currently known 'broken' part of the code) is the documentation. I know that @jabooth and @nontas did a lot of work on it, but could we maybe just collect together here major areas that are known to be broken? This checkboxes below should be updated and kept track of before the release.

  - [x] User Guide
    - Doesn't reflect the package split and a lot of the links are broken because packages have moved around.

The following packages will be handled by those listed:

  - @nontas 
    - [x] feature
    - [x] math
    - [x] visualize
  - @patricksnape
    - [x] image
    - [x] shape
  - @jabooth 
    - [x] landmark
    - [x] io
  - @jalabort 
    - [x] transform
    - [x] model

**Comment by jabooth** [comment]
@nontas did you look over transforms in the end? Just thinking whether we should close this or not..

**Comment by nontas** [comment]
Yup, I fixed it in #553 .
