### ISSUE TITLE
Animation widget doesn't respond after four playbacks

### ISSUE THREAD

**Issue by nontas** [menpo/menpo#578]
The `AnimationOptionsWidget` gets non-responsible after pressing _Play_ and _Stop_ four times. There is no error message. The _Play_ button just doesn't respond any more.

**Comment by patricksnape** [comment]
Maybe something new is getting created every time instead of reused? Therefore, after a few times, the amount of state just gets too much? For example, perhaps some JavaScript is getting fired and event-handlers are getting wired up and after a few times it just gets overloaded?

**Comment by nontas** [comment]
OK, so after the extensive look that @patricksnape had on this, it is not very clear where the bug is. However, I redefined the `AnimationOptionsWidget` in #574 so that it only has a single Play/Stop toggle button instead of two separate ones and this seems to have solved the problem!
