### ISSUE TITLE
return transforms used by Menpo in performing image transformations

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#583]
Menpo makes it easy to perform basic image manipulation:

```python
import menpo
img = menpo.io.import_builtin_asset.lenna_png()
img_scaled = img.rescale(0.5)
```

whilst this is great (as it automatically transforms both the pixels and any attached landmarks) the user is not privy to the transform menpo performed internally. This makes it difficult to confidently apply a 'matching' transformation in the future. As an example, say we landmark the `img_rescaled`, and want to place the rescaled landmarks back on the original image:

```python 
pc = PointCloud(...)  # our landmarks on img_scaled
from menpo.transform import UniformScale
img.landmarks['new_landmarks'] = UniformScale(2.0, n_dims=2).apply(pc)
```
whilst this may seem correct, it's actually subtly wrong (see [Image.resize()](https://github.com/menpo/menpo/blob/master/menpo/image/base.py#L1449) for why).

It would be convenient if users had the ability to directly retrieve the internal transform used by menpo as an advanced option, so they are free to use the transforms for purposes such as this. Furthermore, knowing the original bounds of the image can also be useful, as this allows for manual calls to `Image.warp_to_shape()` for 'undoing' image manipulations. As an example
```python
 original_img = img_scaled.warp_to_shape(transform.pseudoinverse(), original_shape)
```

I propose to add a kwarg to `resize()`, `rescale()`, and `crop()` called `return_transform=False`. Setting this to true will return a tuple of size 2 instead of the usual single image:
```python
img_scaled, transform_info = img.rescale(0.5)
```
the second element of this tuple is itself a `namedtuple`, with keys `transform` and `original_shape`.

**Comment by jalabort** [comment]
I personally do not recall needing this functionality in any of my algorithms but if you find yourself needing these transforms often I'd say this sounds very sensible then.

**Comment by patricksnape** [comment]
I think the biggest use case is:

  1. Load image for fitting
  2. Downscale/crop image before fitting
  3. Fit image
  4. Want to export landmarks that we fit, but for **the original image**, which has now been scaled/cropped.

So that begs the question, how do we get that done? And at the moment, particularly if you called something like ``crop_to_landmarks_inplace``, it is pretty awkward to change the landmarks back into the original space.

**Comment by patricksnape** [comment]
Completed by #631
