### ISSUE TITLE
refactor labels

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#616]
One of the few remaining rough edges of menpo are the landmark labels. 

#### Refactor to package
The [labels module](https://github.com/menpo/menpo/blob/master/menpo/landmark/labels.py) is getting large - it should probably be refactored into a package.

#### Consistent Naming 

The names of the labels have a rough structure to them, but as we add more and more labels it would be nice to have a more consistent naming scheme. I would propose something along the lines of `OBJECTTYPE_IDENTIFIER_NPOINTS{_MODIFIER}`, where:

- `OBJECTTYPE` e.g. `face`, `cat`, `car`
- `IDENTIFIER` the 'name' of the landmark set. E.g. `ibug`, `bu4d`
- `NPOINTS` e.g. `68`

And then, optionally,

- `MODIFIER` e.g. a particular connectivity or variant on a given landmark set (`trimesh`, `v2`)

This is close to what we already use so it's not a huge departure, but it would just be nice to get everything consistent.

#### Labels as callables

Right now each label is a function. This makes it hard to inspect them to find out other information (like the number of points they take). We should move all labels to be small callables with static fields. Suggested properties are:
- `.n_points`: `68`
- `.label`: `face_ibug_68`
- `.object_type`: `face`

**Comment by jabooth** [comment]
@lisracc I believe @patricksnape is planning to tackle this work today - it is a prerequisite to making the menpo -> landmarker.io template transfer work.

I count 31 labels currently in Menpo. Did you make the changes to support a larger list of templates and filtering in the landmarker UI? (it seemed to be there when I checked out the branch over the weekend?)

In doing this work we have an opportunity to make sure these labels are useful for the long haul. Maybe an `object_type` property would be useful metadata to have? That way there could be some option to group labels by type in the landmarker UI? (it wouldn't be something we would have to do now, but we have the option for the future). I've added it to the above suggestions for discussion.

**Comment by lirsacc** [comment]
Filtering and constrained list is in, but yes that is a limited as template are simply template now. However the YAML / JSON definition allows for metadata outside of the `groups` key (which is the template itself) so we can definitely use this down the road to improve the UI.

**Comment by patricksnape** [comment]
I've started working on this because it was getting in the way of some pipeline code I was working on. My one question, @jabooth is about function naming? Is `face_ibug_68_to_face_ibug_66` not quite a long label name? Should we abbreviate these, at least for the `group_label`?

**Comment by jabooth** [comment]
@patricksnape can you propose an abbreviation scheme? I like the formulaic
approach, even if it leads to long names, as any deviation from a pattern
is an exception for the user to remember.

Side note - a reminder that these keys will be used in menpobench too as
yaml keys. Here I agree length is bad, but also in lack of context (no
docstring) formulaic long names are explicit and self documenting.

**Comment by patricksnape** [comment]
@jabooth - OK take a look at what I have, just ignore the doc fixes as that actually takes up a chunk of space.

**Comment by patricksnape** [comment]
This is done by #439
