### ISSUE TITLE
PCAModel only accepts Vectorizable instances

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpo#626]
At the moment, `PCAModel` can only accept lists of `Vectorizable` types. However, if you want to perform PCA on a list of numpy arrays, say, this is not possible. The major issue with this is that, in MenpoFit, if you have a feature that is simply a vector (SIFT -> `128x1`), you cannot currently perform PCA on it due to our `Vectorizable` requirement.

However, this is a sensible restriction at the moment because there are a load of methods such as `instance` that require the `from_vector` functionality.

Possible Solutions
------------------------

  1. Create a dummy `Vector` or `VectorizableWrapper` class that provides `as_vector` and `from_vector`
      - **Pros**: Simple to implement - No changes to `PCAModel`
      - **Cons**: How do we detect this for `PCAModel`? Does `PCAModel` detect it, or do the feature functions return this class? Is that annoying? Should we make PCA calculation a function that returns the correct class/handles this? Similar to `Scale`?
  2. Add a new ``init_from_matrix`` method to `PCAModel`.
      - **Pros**: Simple to implement. Easy interop with a variety of data sources
      - **Cons**: What about the usages of `as_vector`/`from_vector` inside `PCAModel`. Perhaps this is combined with (1) - the `Vector` class?
  3. Make some other class that handles non-`Vectorizable` objects.
      - **Pros**: `PCAModel` stays 'pure'
      - **Cons**: How do we account for this inside of MenpoFit? Detect ala a PCA function (as mentioned in (1))? What about methods like instance? What happens then? Do other methods that rely on `PCAModel` also expect a guarantee that PCA models always return `Vectorizable` instances?

**Comment by nontas** [comment]
I think we need to combine proposals 1 and 2. Specifically:
* Create a `Vector` class that provides dummy implementations of `as_vector()` and `from_vector()`.
* The class should also provide a dummy implementation of `view()` which could either return an error or (preferably) render a histogram with the vector's values.
* It seems a great idea to me to add `init_from_matrix()` in `PCAModel`.

**Comment by patricksnape** [comment]
My major concern is that I **REALLY** don't want to have some `Vector` class that actually gets used. I really really really (I cannot stress this more :P) don't want to start wrapping numpy array classes - they are already amazing at what they do. I feel like maybe, instead of a class, we should just have some sort of method that tries calling `as_vector` and if it can't then it falls back to `ravel`? Then maybe on `from_vector` we duck type something like `original_shape` or something so that we can reshape it easily.

If we do have a class, I don't want it to become public at all - I don't want people to use it in external code! So I don't want the features to return one - at best they should just return a numpy array!

**Comment by patricksnape** [comment]
This is addressed in #645, we decided to go with a base PCA class that accepts numpy arrays.
