### ISSUE TITLE
Python 3.5 update?

### ISSUE THREAD

**Issue by thelostscientist** [menpo/menpo#657]
conda install -c https://conda.anaconda.org/menpo opencv3 for python3? 

sorry no way to open the ticket on the anaconda could

**Comment by jabooth** [comment]
Hi @thelostscientist,

Do you mind opening the issue on the [conda-opencv](https://github.com/menpo/conda-opencv/) repository? This repo is just for the core Menpo Python library. Also the maintainer of the Conda OpenCV bindings, @patricksnape, is currently travelling, so please excuse him if he is unable to get back to you as fast as he would like.

Thanks!

**Comment by zoeith** [comment]
This worked fine: #https://github.com/menpo/conda-opencv3/issues/3
However menpo core fails on a freshly made Python 3.5 environment.
`$ conda create -n menpo python=3.5`
`$ source activate menpo`
`$ conda install -c menpo menpo`

output:
```
The following specifications were found to be in conflict:
  - menpo -> pip
  - menpo -> python 2.7*|3.4*
  - pip (target=pip-8.1.1-py35_0.tar.bz2) -> python 2.7*|3.4*
  - pip (target=pip-8.1.1-py35_0.tar.bz2) -> setuptools
  - python 3.5*
  - setuptools (target=setuptools-20.3-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - wheel (target=wheel-0.29.0-py35_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*
```

**Comment by patricksnape** [comment]
Yes the current release of Menpo does not support Python 3.5 - the next release, coming in the next week or so (0.7.0) does support Python 3.5.
