### ISSUE TITLE
The CLA causes unnecessary friction

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpo#667]
~~Given [this](https://github.com/clahub/clahub/issues/111) and some other linked issues - it seems that CLAHub may be abandoned. Therefore, we need to move to something new ASAP. Given then we've been burned once - perhaps we should set up an instance on the Imperial DOC cloud so we can host everything ourselves? What about something like [cla-assistant](https://github.com/cla-assistant/cla-assistant) which is created by SAP (a very large company) and seems to have easy set-up instructions?~~

@jabooth ?

**Comment by patricksnape** [comment]
CLAHub is no longer dead, it is now being hosted by Berkman Center for Internet and Society at Harvard University.

However, having talked to @JeanKossaifi and then @jabooth it appears that the CLA may be causing unnecessary friction for first time contributors. In particular, the frightening 'legalise' of the document is potentially confusing and really is something akin to a terms of agreement for software (and who ever reads those?). 

Although the CLA was designed to make clear that the developer understands the legal implications of their contribution, it really only serves to confuse the contributor. Since larger projects such as Numpy, Scipy and Scikit-learn do not have CLAs **I am proposing we remove the CLA**. However, I would like confirmation of agreement from all people who have currently signed the CLA. 

Therefore, 

@patricksnape
@evanjbowling
@jalabort
@nontas
@jabooth
@mmcauliffe
@grigorisg9gr

You have all been pinged as a courtesy as you took the time to sign the CLA in the first place. The removal of the CLA has no impact on you and you are not required to do anything but I would appreciate a quick message here that you have seen this and that you agree. **I will replace the CLA with a `contributing.md` that simply states that by opening a PR you are agreeing to the distribution of your PR under the BSD 3-Clause License**.

If anyone disagrees then this issue will serve as the conversation forum so that we might understand the objection.

Menpo has and always will be liberally Open Source, nothing changes, only that we want to make it less 'scary' to contribute 😄.

**Comment by jalabort** [comment]
👍

**Comment by patricksnape** [comment]
👍

**Comment by grigorisg9gr** [comment]
:+1:

**Comment by nontas** [comment]
:+1:

**Comment by mmcauliffe** [comment]
:+1:

**Comment by jabooth** [comment]
👍

**Comment by evanjbowling** [comment]
Fine with me

**Comment by patricksnape** [comment]
Thanks everyone! The CLA is now removed - I will update the contributing.md shortly.
