### ISSUE TITLE
Importing custom file types should be simpler

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpo#689]
At the moment, though possible, it is a pain to add a new custom extension to the importers. There is a bit of a complex hierarchy to the builders that I'm not sure is necessary. I think we should remove all the object orientation and just make it functional - so you just provide a function that returns a specific format, say a custom tuple or even the correct type itself, and then we add a hook to the `io` package for registering these methods.

Something like 

```
import menpo.io as mio

def custom_importer(filepath, asset=None):
    return Image.init_blank((10, 10))

mio.register_image_importer('.foo', custom_importer)
foo_image = mio.import_image('/path/to/foo')
```

We could even add a more generic importing chain (if we wanted) just based on 'assets' that can return any type.

**Comment by jabooth** [comment]
Yeah I think this is a wonderful idea, would simplify things down in the `io` module nicely. If we went down this road it might be worth considering URLs as sources too, and handling those cases (especially useful for example notebooks with data dependencies)

**Comment by jabooth** [comment]
Note that this is currently WIP and @patricksnape has already submitted the PR https://github.com/menpo/menpo/pull/694

**Comment by patricksnape** [comment]
#694 was merged and closes this issue.
