### ISSUE TITLE
Is exact_frame_count in FFMpegVideoReader used?

### ISSUE THREAD

**Issue by san-bil** [menpo/menpo#715]
It looks like -count_frames is being passed to ffprobe no matter than value of the `exact_frame_count` attribute in `FFMpegVideoReader`, so each call to `menpo.io.import_video` is taking a *long* time for videos measured in minutes.

**Comment by patricksnape** [comment]
Yes that is questionable behaviour (see [here](https://github.com/menpo/menpo/blob/master/menpo/io/input/video.py#L90)) where we basically assume that `exact_frame_count` doesn't actually change behaviour but just *allows* the fall back as opposed to throwing an error.

So @san-bil you would prefer to be able to forgo the accurate frame count completely to improve loading speed? I would warn that in this case it is highly likely that the frames you receive from ffmpeg have no relationship to the underlying key frames and you may end up receiving out of bounds/closed pipe exceptions when reading frames at the 'end' of the video!

**Comment by san-bil** [comment]
OutOfBounds exceptions near the end are understandable (and are tolerable since I'm extracting lots of random subsequences, so I can just catch them and try again, or allow some margin at the end of the video), but I how would the frames be "unrelated" to the underlying keyframes? Aren't frames delivered from ffmpeg in the same manner, assuming you don't go out of bounds?

**Comment by patricksnape** [comment]
Fixed by #716
