### ISSUE TITLE
Vertex_normals() supported types

### ISSUE THREAD

**Issue by Loubnar** [menpo/menpo#718]
I am currently working on a 3D Morphable Model in the form of a `ColouredTriMesh`, where the type of `points` is `float32` and that of `trilist` is `uint16`. Calling `vertex_normals()` on this mesh is only possible when `points` and `trilist` types are converted due to the small list of supported types:
https://github.com/menpo/menpo/blob/master/menpo/shape/mesh/normals.pyx#L7-L11

Maybe the list should be extended ?

**Comment by jabooth** [comment]
@patricksnape see you've already made a start on this, cheers!

Would be good to time cythonized triangle/vertex normal code against vectorised alternatives, didn't realise it was possible to vectorize vertex normals as seen here:
https://github.com/menpo/cyrasterize/blob/master/cyrasterize/glrasterizer.pyx#L126

May well still be faster-enough to justify the maintenance burden of cython, but if not always good to simplify the code base...

**Comment by patricksnape** [comment]
<img width="429" alt="screenshot 2016-08-01 16 52 58" src="https://cloud.githubusercontent.com/assets/708474/17298056/b7fc33fc-5808-11e6-855c-b8881430a01c.png">

Cythonized version is twice as fast 😄
