### ISSUE TITLE
Consider supporting Python 3 2020 statement

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#721]
A nice effort to promote the move to Python 3:
https://python3statement.github.io/

Projects commit to remove support for Python 2 by 2020 (which is when official support is due to end). Some projects are moving well before that date.

It's important to note this list includes IPython, which gives extra credibility to the idea that the scientific Python world may well make the jump.

Menpo is a small project, but we are a well organised one. We are quite capable of retaining Python 2.7 support for a long time, but we could equally decide that we would rather start benefitting from the growing list of Python 3 only features sooner.

Anyone using Menpo, feel free to weigh in here.

**Comment by patricksnape** [comment]
I would be happy to drop Python 2.x support on January 1st 2020.

**Comment by jabooth** [comment]
I would be happy with that, but could also be happier earlier than that.

For some context, [our first commit was Nov 12, 2012](https://github.com/menpo/menpo/commit/97c99298686b25ef2f2f531128f0fb04b2f4d86d), so just over 3 1/2 years ago.

Jan 1, 2020 is nearly the same length of time away from us now.

For our internal use, a move to Python 3 would be relatively straightforward (I think most are already there as it stands). It's more difficult to know how others are using menpo though, and in what environments. 

Maybe we should try and get some feedback on the mailing list on how people are using us?

**Comment by patricksnape** [comment]
I think the last time I saw numbers 2.7 still represented the *vast* majority of Python users. Perhaps when that number shifts?

**Comment by grigorisg9gr** [comment]
+1 to James on python 3. 

Probably the easiest would be to make the python 3 the default one for conda and the rest menpo installations.

**Comment by jabooth** [comment]
Just posted to the mailing list about this to get more feedback:
https://groups.google.com/forum/#!topic/menpo-users/HIjm4B3zCGs

**Comment by patricksnape** [comment]
Python 2 support is dropped. If you want to officially sign the support statement please feel free to do so our open a new issue for that specifically.
