### ISSUE TITLE
Proposal: automatically migrate older PCAModel instances

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#725]
Although not merged yet, in preparing the big upcoming change to Landmarks (#675) we started to get a feel for how to [transparently migrate older data structures in Python](https://github.com/patricksnape/menpo/blob/a4a65bc983b731018281eea745a9ebec20f35e2f/menpo/landmark/base.py#L324):
```py
# TODO: Deprecate this - this handles importing old-style LandmarkGroup
class LandmarkGroup(object):

    def __new__(cls, *args, **kwargs):
        # This is a crazy hack that means when old style LandmarkGroup
        # objects are imported it is actually new-style LandmarkGroups
        # that are created.
        from menpo.shape import LandmarkGroup as NewLandmarkGroup
        return NewLandmarkGroup.__new__(NewLandmarkGroup, *args, **kwargs)
```
if we think about this carefully we could probably add a similar logic for `PCAModel` that was broken in #645. I've got a bunch of old model pickles laying around that I keep hitting this issue with.

**Comment by jabooth** [comment]
FWIW, my migration code has been:
```py
# the definition of the Menpo PCA model changed for 0.6.0. Here we migrate old
# pickled models to the new version.
def migrate_menpo_pca_model(m):
    mean = m.template_instance.from_vector(m.__dict__['mean_vector'])
    return m.init_from_components(m._components, m._eigenvalues, mean,
                                  m.__dict__.get('n_samples'), m.centred)
```
Although from memory I think you have a cleaner one @patricksnape?

**Comment by patricksnape** [comment]
As discussed, I think this can be relatively simply supported by just overriding ``__reduce__`` on `PCAModel`

**Comment by patricksnape** [comment]
Done in #728
