### ISSUE TITLE
Conda-forge builds

### ISSUE THREAD

**Issue by anjos** [menpo/menpo#730]
Any chance this package + dependencies will be included in [conda-forge](https://github.com/conda-forge) any time soon?

**Comment by patricksnape** [comment]
Yes I'm slowly transitioning some of the packages to conda-forge - but some of the packages have proven very difficult to build within the conda-forge environment such as dlib and opencv. Once they are built, then I will transition menpo up as it should be relatively simple.

**Comment by patricksnape** [comment]
List of packages we need for menpo to be on conda-forge:
    - [ ] python
    - [ ] setuptools
    - [ ] cython
    - [ ] pathlib 1.0
    - [ ] numpy
    - [ ] scipy
    - [ ] pillow
    - [ ] ffmpeg
    - [ ] cyvlfeat
      - [ ] vlfeat
    - [ ] matplotlib
    - [ ] mock
    - [ ] nose

**Comment by patricksnape** [comment]
Numpy and Scipy are going to be a real problem as we need them for Windows.

**Comment by jabooth** [comment]
@patricksnape minor-ish point, but as I understand it conda-forge is exclusively openBLAS as opposed to MKL? If so, our NICP performance will take a huge hit (cholesky decomp just seems way slower for openBLAS vs MKL).

Would it make sense to get linux/macOS builds on conda-forge as a first priority? We don't want to get into an indefinite state of straddling our own builds on the menpo channel and conda forge, but it may make sense to do linux/macOS as a first stage, and allow some time for the wider community to solve numpy/scipy on windows?

**Comment by patricksnape** [comment]
Yeah OpenBLAS only sucks too. Just such a pain when there are so many good packages on conda-forge already. Tough to know where to draw the line but unless Intel releases MKL for free we don't have a lot of choice. I'd be happy to do OSX/Linux builds though.

**Comment by patricksnape** [comment]
This is now done for `menpo`
