### ISSUE TITLE
menpo.feature.glyph non-integer warning

### ISSUE THREAD

**Issue by ampersd** [menpo/menpo#746]
I'm trying to go through menpo-notebooks tutorials. Have some warning (see picture). Now it works, but can cause problems in future. Don't know what is preferable way to notify you about little things like this: issues on github or this [group](https://groups.google.com/forum/#!forum/menpo-users). 
Maybe it will be good to write to README.md about preferable way to communicate (group, github or email), when someone find bug or unexpected behavior.

![2016-09-25_21-48-02](https://cloud.githubusercontent.com/assets/6360879/18816908/9bb9cbf2-836c-11e6-81a6-9d5f5128a89c.png)
![2016-09-25_21-50-25](https://cloud.githubusercontent.com/assets/6360879/18816909/9e9200ba-836c-11e6-8323-ac2feaef7dba.png)

Also I was trying to run 'nosetests .' in menpo repo folder and it's failed.

**Comment by patricksnape** [comment]
If you feel that this is an issue with the code, then this is the correct place. If you want help building an AAM - or are getting issues todo with installation or something like that - the group is the right place. Thanks for bringing this to our attention - I'll put it on my TODO list.

**Comment by patricksnape** [comment]
The `glyph` features are now removed.
