### ISSUE TITLE
md5sum mismatch for menpo_py package.

### ISSUE THREAD

**Issue by gp1313** [menpo/menpo#772]
Conda was successfully installed. While installing menpo packages using command "conda install -c menpo menpoproject" md5sum mismatch occurs.
  
System detail : ubuntu 14.04, 64 bit.

**Comment by gp1313** [comment]
package name : 0.7.6-py27_0

**Comment by patricksnape** [comment]
That sounds like your connection is failing or it cached a broken version? You didn't provide a package name above but it looks like menpo itself which is strange. I can't replicate that locally.

**Comment by gp1313** [comment]
package name : 0.7.6-py27_0

**Comment by gp1313** [comment]
In order to debug this I did separately download the package 0.7.6-py27_0 from the link that conda package manager uses to install this package. I ran MD5Sum check on this file and found it to be different than the one present in respective .json conda file. I had to replace original md5Sum value by this value! 

This small hack worked for me.
