### ISSUE TITLE
normalize=False changes masking behavior for images with alpha channel

### ISSUE THREAD

**Issue by jabooth** [menpo/menpo#773]
To reproduce:

1. Load this test image:
![image](https://cloud.githubusercontent.com/assets/1312873/21684059/1169ed46-d354-11e6-8317-9e8199411178.png)

2. Run
```python
import menpo.io as mio
print(mio.import_image('test.png'))
```
```
640W x 480H 2D MaskedImage with 3 channels. Attached mask 100.0% true
```

3. Run
```python
import menpo.io as mio
print(mio.import_image('test.png', normalize=False))
```
```
640W x 480H 2D Image with 4 channels
```
I didn't expect the interpretation of the alpha channel to change based on the `normalize` flag - I think instead we should handle the alpha channel exactly as before (producing in this case a 3D `np.unit8` `MaskedImage` (RGB, A) rather than a 4D `np.unit8` `Image` (RGBA)).

Could see the `normalize` kwarg is a _'stop being clever menpo and give me the raw data'_ flag, but then at least we need to document it that way.

**Comment by patricksnape** [comment]
> Could see the normalize kwarg is a 'stop being clever menpo and give me the raw data' flag, but then at least we need to document it that way.

That's how I implemented that. Because alpha channels can be `[0, 255]` so our masking is actually a pain if you *want* the values in the alpha channel.

**Comment by patricksnape** [comment]
We agreed to just change the documentation to make this behaviour clear.
