### ISSUE TITLE
 pre-unlink script failed for package menpo::widgetsnbextension-1.2.3-py35

### ISSUE THREAD

**Issue by LindaSt** [menpo/menpo#797]
When I am trying to update the conda packages (`conda update --all`) I get the following warning: 

> WARNING conda.core.link:run_script(517): pre-unlink script failed for package menpo::widgetsnbextension-1.2.3-py35_1 consider notifying the package maintainer

I am on the conda version 4.3.15 and added menpo with `conda config --add channels menpo`

**Comment by patricksnape** [comment]
This shouldn't be a problem - we are working on updating menpowidgets to use a more up to date widgets package so that we don't need to maintain our own.
