### ISSUE TITLE
'module' object has no attribute 'to_rgba'

### ISSUE THREAD

**Issue by cangyue080180** [menpo/menpo#825]
windows 10
miniConda 4.5.11
menpo 0.8.1
matplotlib 1.5.3
when I used menpo visual in jupyter notebook ,always has the error:

D:\ProgramFiles\Miniconda3\envs\menpo\lib\site-packages\ipykernel\pylab\backend_inline.pyc in _is_transparent(color)
    193 def _is_transparent(color):
    194     """Determine transparency from alpha."""
--> 195     rgba = colors.to_rgba(color)
    196     return rgba[3] < .5

AttributeError: 'module' object has no attribute 'to_rgba'

some one say I hava to upgrade the matplotlib,but I get the other error:

menpo 0.8.1 has requirement matplotlib<2.0,>=1.4, but you'll have matplotlib 2.2.0 which is incompatible.

Can you help me?

**Comment by theandrewchan** [comment]
Just wanted to comment that this is caused by the newer ipykernel versions using matplotlib 2.0 when you set `%matplotlib inline`, and can be fixed by downgrading ipykernel to 4.7.0, with `conda install ipykernel=4.7.0`.

**Comment by rubenmiguelborges** [comment]
I had the same issue and theandrewchan's post gave me the idea of updating all before trying to downgrade, so I did "conda update --all" and it sorted out the issue.

**Comment by jaredthomas68** [comment]
After seeing @rubenmiguelborges answer, I decided to be more selective in my updating, and it worked as well. I did the following:

$ conda update matplotlib
$ conda update numpy

These commands also update all the dependencies of matplotlib and numpy. Jupyter is plotting like a charm now.
