### ISSUE TITLE
Jupyter Notebooks .lms deprecated and Attribute Error:

### ISSUE THREAD

**Issue by danindiana** [menpo/menpo#826]
When trying to run through tutorials 
![menpoerrorscrenshot](https://user-images.githubusercontent.com/3030588/52118802-ec5c1000-25dc-11e9-9536-42987d874b45.jpg)
Jupyter Notebooks throws the following error(s): 

/home/johnh/.conda/envs/menpo/lib/python2.7/site-packages/menpo/shape/pointcloud.py:261: MenpoDeprecationWarning: The .lms property is deprecated. LandmarkGroups are now shapes themselves - so you can use them directly anywhere you previously used .lms.Simply remove ".lms" from your code and things will work as expected (and this warning will go away)
  MenpoDeprecationWarning)

and AttributeError: 'module' object has no attribute 'to_rgba'

$jupyter notebook
[I 04:34:19.797 NotebookApp] Serving notebooks from local directory: /home/johnh/gits/menpo-notebooks
[I 04:34:19.797 NotebookApp] The Jupyter Notebook is running at:
[I 04:34:19.797 NotebookApp] http://localhost:8888/?token=9945df7fc146d8ab8dacf1b9fe963affffc099f2d73a0ccc
[I 04:34:19.797 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 04:34:19.799 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///run/user/1000/jupyter/nbserver-641-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=9945df7fc146d8ab8dacf1b9fe963affffc099f2d73a0ccc
[W 04:34:29.046 NotebookApp] Notebook menpo/Landmarks/Basics.ipynb is not trusted
[I 04:34:30.610 NotebookApp] Kernel started: 418a7b2c-9dec-4c7b-aea5-f6ac8584ae42
[I 04:34:30.898 NotebookApp] Adapting to protocol v5.1 for kernel 418a7b2c-9dec-4c7b-aea5-f6ac8584ae42
[I 04:36:30.693 NotebookApp] Saving file at /menpo/Landmarks/Basics.ipynb
[W 04:36:30.694 NotebookApp] Notebook menpo/Landmarks/Basics.ipynb is not trusted
[I 04:40:30.696 NotebookApp] Saving file at /menpo/Landmarks/Basics.ipynb
[W 04:40:30.697 NotebookApp] Notebook menpo/Landmarks/Basics.ipynb is not trusted

All python Versions: 

ls -ls /usr/bin/python*
   0 lrwxrwxrwx 1 root root       7 Jun  7  2018 /usr/bin/python -> python2
   0 lrwxrwxrwx 1 root root       9 Jun  7  2018 /usr/bin/python2 -> python2.7                                                                                                                                    
3608 -rwxr-xr-x 1 root root 3690840 Oct  2 17:12 /usr/bin/python2.7                                                                                                                                               
   0 lrwxrwxrwx 1 root root      33 Oct  2 17:12 /usr/bin/python2.7-config -> x86_64-linux-gnu-python2.7-config                                                                                                   
   0 lrwxrwxrwx 1 root root      16 Jun  7  2018 /usr/bin/python2-config -> python2.7-config                                                                                                                      
   0 lrwxrwxrwx 1 root root       9 Oct 25 06:11 /usr/bin/python3 -> python3.6                                                                                                                                    
4436 -rwxr-xr-x 2 root root 4538776 Jan 14 05:02 /usr/bin/python3.6                                                                                                                                               
   0 lrwxrwxrwx 1 root root      33 Jan 14 05:02 /usr/bin/python3.6-config -> x86_64-linux-gnu-python3.6-config                                                                                                   
4436 -rwxr-xr-x 2 root root 4538776 Jan 14 05:02 /usr/bin/python3.6m                                                                                                                                              
   0 lrwxrwxrwx 1 root root      34 Jan 14 05:02 /usr/bin/python3.6m-config -> x86_64-linux-gnu-python3.6m-config                                                                                                 
   0 lrwxrwxrwx 1 root root      16 Oct 25 06:11 /usr/bin/python3-config -> python3.6-config                                                                                                                      
   0 lrwxrwxrwx 1 root root      10 Oct 25 06:11 /usr/bin/python3m -> python3.6m                                                                                                                                  
   0 lrwxrwxrwx 1 root root      17 Oct 25 06:11 /usr/bin/python3m-config -> python3.6m-config                                                                                                                    
   0 lrwxrwxrwx 1 root root      14 Jun  7  2018 /usr/bin/python-config -> python2-config       

whereis python
python: /usr/bin/python /usr/bin/python2.7 /usr/bin/python3.6-config /usr/bin/python3.6 /usr/bin/python2.7-config /usr/bin/python3.6m-config /usr/bin/python3.6m /usr/lib/python2.7 /usr/lib/python3.6 /usr/lib/python3.7 /etc/python /etc/python2.7 /etc/python3.6 /usr/local/lib/python2.7 /usr/local/lib/python3.6 /usr/include/python2.7 /usr/include/python3.6 /usr/include/python3.6m /usr/include/python3.7m /usr/share/python /home/johnh/miniconda3/bin/python /home/johnh/miniconda3/bin/python3.7m-config /home/johnh/miniconda3/bin/python3.7-config /home/johnh/miniconda3/bin/python3.7 /home/johnh/miniconda3/bin/python3.7m /usr/share/man/man1/python.1.gz

OS: Ubuntu 18.10 cosmic
 Kernel: x86_64 Linux 4.18.0-13-generic
 Uptime: 1d 9h 58m
 Packages: 2437
 Shell: bash 4.4.19
 Resolution: 1920x1200
 DE: LXDE
 WM: OpenBox
 CPU: Intel Xeon W-2125 @ 8x 4.5GHz [30.0°C]
 GPU: Quadro P4000
 RAM: 3118MiB / 31821MiB

**Comment by patricksnape** [comment]
Latest notebooks are fixed for menpo (https://nbviewer.jupyter.org/github/menpo/menpo-notebooks/blob/master/menpo/Landmarks/Basics.ipynb)
