### ISSUE TITLE
Export landmarks

### ISSUE THREAD

**Issue by bikekowal** [menpo/menpo#827]
Hi,

I am trying to export landmarks to file, i.e. csv or json. 

When using this piece of code:
`res = fitter.fit_from_bb(img, img.landmarks["bb"].lms)
menpo.io.export_landmark_file(res, 'text.ljson', extension=None, overwrite=True)`

I am receiving the following error 

> 
AttributeError: 'AAMResult' object has no attribute 'tojson'

**Comment by patricksnape** [comment]
As the error states, `res` is not a `Shape` subclass -> Use the `final_shape` attribute to access the final shape.
