### ISSUE TITLE
convex hull issues

### ISSUE THREAD

**Issue by voodoopotato** [menpo/menpo#828]
I have an Image object with these points as landmark:
`pts = [[102, 466], [66, 511], [39, 591], [31, 690], [52, 794], [98, 870], [155, 913], [228, 916], [336, 898], [436, 874], [524, 857], [622, 830], [694, 764], [740, 681], [761, 599], [738, 499], [733, 475], [102, 466]]`
I plan to use these as mask on an Image.
my code is:
`pts = PointCloud(self.boundaries)`
`img.landmarks['boundary'] = pts`
`mask_img = img.as_masked()`
`mask_img_constrained = mask_img.constrain_mask_to_landmarks(group ='boundary')`
What the convex hull should look like 
![myplot2](https://user-images.githubusercontent.com/25180887/58754226-56a09680-8491-11e9-9fd9-55fd63040051.png)
what I got:
![myplot](https://user-images.githubusercontent.com/25180887/58754195-d417d700-8490-11e9-8b85-ca154fd5288f.png)
Can anyone help??

**Comment by patricksnape** [comment]
I don't see that running on master:

![image](https://user-images.githubusercontent.com/708474/61009609-8043bc00-a373-11e9-94d3-c1f425fd5cc8.png)
