### ISSUE TITLE
'conda install -c menpo/channel/master menpo' fails

### ISSUE THREAD

**Issue by hugeinteger** [menpo/menpo#831]
I'm trying to set up dev environment for menpo like it's described in https://www.menpo.org/installation/development.html.

But the installation constantly fails. I'm getting below errors when running
conda install -c menpo/channel/master menpo

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package nose conflicts for:
menpo -> nose
Package matplotlib conflicts for:
menpo -> matplotlib[version='>=1.4,<2.0']
Package cyvlfeat conflicts for:
menpo -> cyvlfeat[version='>=0.4.3,<0.5']
Package scipy conflicts for:
menpo -> scipy[version='>=0.16,<1.0']
Package pathlib conflicts for:
menpo -> pathlib==1.0
Package pip conflicts for:
python=3.5 -> pip
Package numpy conflicts for:
menpo -> numpy[version='>=1.10,<2.0']
Package vs2015_runtime conflicts for:
python=3.5 -> vs2015_runtime
Package mock conflicts for:
menpo -> mock
Package vc conflicts for:
python=3.5 -> vc=14
Package pillow conflicts for:
menpo -> pillow[version='>=3.0,<4.0|>=3.0,<5.0']
Package ffmpeg conflicts for:
menpo -> ffmpeg[version='>=2.7,<3.0']

BTW: I'm running in python 3.5 environment created like below:
conda create -n menpo_dev python=3.5

Are there any suggestion on how to solve these issues?

Thanks!

**Comment by patricksnape** [comment]
Unfortunate timing! I'm in the middle of migrating everything to conda-forge and I haven't updated the website yet.

Try this:
```
conda install -c menpo/channel/master -c conda-forge menpo
```

Note that Python 3.5 is no longer supported for conda builds - only Python 3.6 and Python 3.7

**Comment by patricksnape** [comment]
Also windows builds are no longer automatically supported.

**Comment by hugeinteger** [comment]
> Unfortunate timing! I'm in the middle of migrating everything to conda-forge and I haven't updated the website yet.
> 
> Try this:
> 
> ```
> conda install -c menpo/channel/master -c conda-forge menpo
> ```
> 
> Note that Python 3.5 is no longer supported for conda builds - only Python 3.6 and Python 3.7

Thanks a lot! It worked for me finally :)

**Comment by patricksnape** [comment]
Also note that menpo is also hosted on conda-forge directly so you don’t need to install from master if you don’t need the bleeding edge builds. You can just choose conda-forge 

‘conda install -c conda-gorge menpo

**Comment by tiancaipipi110** [comment]
@patricksnape Hi,  `conda install -c conda-forge menpo` will get 
```
PackagesNotFoundError: The following packages are not available from current channels:

  - menpo

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```
`conda install -c menpo/channel/master -c conda-forge menpo` will get the same `UnsatisfiableError: The following specifications were found to be incompatible with each other:` error. 

> Also windows builds are no longer automatically supported.

And what do you mean by this? Those commands don't run on Windows anaconda? Then how to install it on Windows manually?

**Comment by patricksnape** [comment]
No the current builds are actually only against Python 3.6 and Python 3.7. If you want to use the latest version of menpo I suggest you just install it like:

```
conda install -c conda-forge menpo
```

If you really need the master version for some reason please let me know and I can try cut a new release to stop you from needing to install from our master builds. Only menpo developers should ever need to do this ideally.

**Comment by patricksnape** [comment]
Note that as long as you have a compiler, Cython and Numpy installed it should also be possible to install menpo via `pip install menpo` - we are actually working on trying to remove all Cython code where possible to reduce this friction.

**Comment by tiancaipipi110** [comment]
Tried` conda install -c conda-forge menpo`, & `conda install -c menpo/channel/master -c conda-forge menpo`, all give me 
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Package cython conflicts for:
Bunch of packages.
```
And the only way I can get it installed is to specify python=3.5, not even python=3.6.

**Comment by patricksnape** [comment]
Sounds like your environment already has conflicting packages inside. Try creating a fresh Conda environment and make sure all your packages are from conda Forge.

Or just try pip install it

**Comment by tiancaipipi110** [comment]
Already installed through `conda install -c menpo/channel/master -c conda-forge menpo python=3.5`. Those failed attempts were all in a fresh environment.

Btw, do you happen to know what` ValueError: Number of weightings cannot be greater than 104`
I was reconstructing image through
`recon_images = aam.appearance_reconstructions(result.appearance_parameters, result.n_iters_per_scale)`

**Comment by patricksnape** [comment]
Yes the latest build matrix no longer supports Python 3.5 so it won't install with Python 3.5. The Menpo channel and conda-forge are only compatible from Python 3.6 and later.

For your second question you will need to open a new issue with a reproducible example unfortunately as I don't know what's wrong there :(

**Comment by tiancaipipi110** [comment]
ok, btw+, do you happen to know how to mask/filter the 68 landmarks so it only shows lower face (lower jaw, mouth)? :)

**Comment by patricksnape** [comment]
```
import menpo

image = menpo.io.import_builtin_asset.lenna_png()
image = image.as_masked()

image.landmarks['mouth_and_lower_jaw_only'] = image.landmarks['LJSON'].add_label('lower_jaw', range(5, 12)).with_labels(['mouth', 'lower_jaw'])

masked_image = image.constrain_mask_to_landmarks(group='mouth_and_lower_jaw_only')

masked_image.view()
```

**Comment by patricksnape** [comment]
Locking this issue as it is now really off topic, please open a new issue for new questions 😄
