### ISSUE TITLE
PWA : AttributeError: 'numpy.ndarray' object has no attribute '_transform'

### ISSUE THREAD

**Issue by ScottHoang** [menpo/menpo#834]
python version: 3.6.7
menpo version: 0.8.1
numpy version: 1.14.5 

----------------------------------------code-------------------
from menpo.image import Image
from menpo.transform import PiecewiseAffine
import cv2

src = [[x,y],...]
tgt = [[x,y]...]
image_array = cv2.imread(...)

pwa_tgt_to_src = PiecewiseAffine(source=PointCloud(src), target=PointCloud(tgt))

image = Image(image array)

warped = image.warp_to_shape(image_array.shape[:2], pwa_tgt_to_src, order=3, batch_size=3000)

---------------------------------------------------------error
error 1:
AttributeError: 'numpy.ndarray' object has no attribute '_transform' -> occur on line 184 under menpo\transform\base\__init__.py

error 2:
During handling of the above exception, another exception occurred:
menpo.transform.piecewiseaffine.base.TriangleContainmentError
-------------------------------------------------------------------
can anyone help?
I also want to point out that thinplateSpline works fine.

[update]
trying with the latest version of menpo, v0.9.2, yield identical errors.

**Comment by patricksnape** [comment]
Can you provide any test data? To replicate the issue?
