### ISSUE TITLE
Not able to install complete menpoproject over linux environment

### ISSUE THREAD

**Issue by prasanthss1991** [menpo/menpo#835]
I have followed below page for the menpoproject installation
https://www.menpo.org/installation/linux/beginner.html

But it fails with following error:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package menpo3d conflicts for:
menpoproject -> menpo3d
Package menpofit conflicts for:
menpoproject -> menpofit
Package python conflicts for:
menpoproject -> python
Package menpodetect conflicts for:
menpoproject -> menpodetect
Package menpocli conflicts for:
menpoproject -> menpocli
Package menpowidgets conflicts for:
menpoproject -> menpowidgets
Package menpo conflicts for:
menpoproject -> menpo

**Comment by prasanthss1991** [comment]
while executing the following
(menpo)$ conda install -c menpo menpoproject

**Comment by patricksnape** [comment]
This is no longer supported - I have updated the website. Please install from `conda-forge`:

```
conda install -c conda-forge menpo
```
