### ISSUE TITLE
Removal of Glyph function breaks menpowidget 

### ISSUE THREAD

**Issue by apapaion** [menpo/menpo#836]
Menpowidget packages doesnt work any more since it needs Glyph function. 
Is it a good idea to add it back with replacing imrotate (from scipy.misc) with  rotate(from skimage.transform)?

**Comment by patricksnape** [comment]
I'm curious to know if you have the widgets working at all? Because as far as I can see the widgets are totally broken with any recent version of notebooks? My current plan of action was actually to delete the widgets entirely.

**Comment by apapaion** [comment]
Yes, menpowidgets work pretty well even for 3D (meshes, models e.t.c.). I haven't checked them with JupyterLab though.

**Comment by patricksnape** [comment]
What version of jupyter notebook and ipywidgets are you using because they don't work for me at all?

**Comment by apapaion** [comment]
Here they are:
ipykernel                 4.10.0                   py35_0  
ipython                   6.5.0                    py35_0  
ipython_genutils          0.2.0            py35hc9e07d0_0 
ipywidgets                6.0.1                    pypi_0    pypi
jupyter                   1.0.0                    py35_7  
jupyter_client            5.3.3                      py_0  
jupyter_console           5.2.0            py35h4044a63_1  
jupyter_core              4.5.0                      py_0 
notebook                  5.6.0                    py35_0

**Comment by patricksnape** [comment]
Latest menpowidgets is alive again! Haven't made a release but master should work
