### ISSUE TITLE
What could be the minimum hassle way to install menpo on Windows?

### ISSUE THREAD

**Issue by colt18** [menpo/menpo#837]
As the title says, after the recent changes I simply can't install the menpo on Anaconda Windows. Is there an automated process so we could install it with minimum hassle? 

And please gifff us windows automated installation thing. It was a relief.

**Comment by tabahi84** [comment]
I was able to install menpo on WIndows 10 by installing Anaconda2 4.2.0 (64 bit) and later installing menpo using following spec-file

Best of luck

[spec-file.txt](https://github.com/menpo/menpo/files/3937316/spec-file.txt)

**Comment by patricksnape** [comment]
You should be able to pip install menpo on Windows up to the C-extensions - I'm working on removing all the C-extensions such that menpo is a pure Python package which means it trivially installs on Windows. Building C-extensions on Windows is a lot of work and unfortunately I consider it beyond my efforts given the open source nature of the package

**Comment by patricksnape** [comment]
Note that after #839 and #818 and #822 being merged `menpo` is a Pure Python package that should install using pip cleanly on any system
