### ISSUE TITLE
Changing License to be totally unmodified BSD 3 license

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpo#840]
# Copyright Holders

- [x] @jabooth
- [x] @nontas
- [x] @jalabort
- [x] @grigorisg9gr
- [x] @mmcauliffe
- [x] @JeanKossaifi
- [ ] @san-bil
- [x] @georgesterpu
- [x] @evanjbowling
- [x] @dubzzz

# TL;DR
Want to simplify the license to a plain old BSD-3 clause with no modifications at all.
**Please comment here that you agree with this.**

# Issue
I've identified you all as people who have committed at least one commit to menpo. I've had requests to update the license to reflect the fact that the license is meant to be a generic BSD-3 clause but it actually contains some modified lines. The diff is below (taken from the License.txt from https://github.com/menpo/menpo/commit/5535bc100140edf08f15a159b13cb44dbfb2f463) and the BSD-3 clause template taken from https://opensource.org/licenses/BSD-3-Clause):

```
@@ -1,6 +1,4 @@
-Copyright (c) 2014, Imperial College London and others. Please see the
-AUTHORS file in the main source directory for a full list of copyright
-holders. All rights reserved.
+Copyright <YEAR> <COPYRIGHT HOLDER>
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
@@ -10,16 +8,15 @@
     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
-    * The name of Imperial College London or that of other
-      contributors may not be used to endorse or promote products
+    * Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written
       permission.
 
-THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTERS
-''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
+THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
+"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
+HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
```

Note that I have added line breaks to the license from https://opensource.org/licenses/BSD-3-Clause to reduce the number of diffs but no other changes have been made.

As you can see, the differences in the all caps disclaimer text are just minor formatting and spelling changes that will be reverted.

For transparency - we originally copied the Scipy license https://www.scipy.org/scipylib/license.html as we were unsure whether Imperial had any copyright claim at the time. 

# Proposed Change
The copyright and copyright naming lines were naively modified to explicitly say a copyright holders name rather than the usual `the copyright holder`. I would likely to change the license to the below:

```
Copyright 2014,  Menpo Developers

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by patricksnape** [comment]
Note that I don't think I'm required to do this but I wanted to be transparent - if anyone doesn't reply in a timely fashion and the majority agree I will likely go ahead with this.

**Comment by jabooth** [comment]
Didn't even know we weren't on the 100% standard format - seems fine to me!

**Comment by evanjbowling** [comment]
I’m fine with this change - thanks for being transparent.

**Comment by georgesterpu** [comment]
I have only fixed a couple of docstring typos :smile: 
This is all your hard work and I don't deserve the right to pass any judgement on your proposal.
Please feel free to exclude me from this.

**Comment by nontas** [comment]
Thanks for taking care of this @patricksnape !

**Comment by JeanKossaifi** [comment]
I'm all in favor of BSD 3 :)

**Comment by grigorisg9gr** [comment]
Thanks once again Patrick for the work! No objection on my part.

**Comment by patricksnape** [comment]
@san-bil @dubzzz I'm going to set a date to get this done of **January 24 2020** so would be great if you could reply before then. If you don't reply I'm going to go with the majority here and put this through.

Thanks!

**Comment by patricksnape** [comment]
The proposed PR is here:

https://github.com/menpo/menpo/pull/841

Feel free to check that the modifications are as discussed.

**Comment by dubzzz** [comment]
@patricksnape Sorry for the delay, LGTM

**Comment by patricksnape** [comment]
This is now done: https://github.com/menpo/menpo/pull/841

Thanks everyone!
