### ISSUE TITLE
Not able to install menpowidgets using conda

### ISSUE THREAD

**Issue by mrkoujan** [menpo/menpo#846]
It seems menpowidgets is not installable using any of the Anaconda channels available here:
https://anaconda.org/menpo/menpowidgets
It keeps producing the following error:
Solving environment: failed with initial frozen solve.
PackagesNotFoundError: The following packages are not available from current channels:
- menpowidgets

**Comment by darshan94** [comment]
I guess feature removed by dev

**Comment by patricksnape** [comment]
This is super old but I actually did just update menpowidgets to work again - still need to release a package but installing off of master should work:

https://github.com/menpo/menpowidgets
