### ISSUE TITLE
Unable to install Menpo through Conda on Windows

### ISSUE THREAD

**Issue by KyleMcMullan** [menpo/menpo#848]
Apologies if this has already been asked but I couldn't find it anywhere.

I run the code as suggested in the installation guide:
`conda install -c conda-forge menpo`

And it returns this:

'Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - menpo

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch`

Sorry about the formatting.

**Comment by patricksnape** [comment]
Yes windows isn't supported at the moment via conda. As I slowly remove all the Windows build requirements I may reenable this.

**Comment by VictorFlavio123** [comment]
> 
> 
> Yes windows isn't supported at the moment via conda. As I slowly remove all the Windows build requirements I may reenable this.

Hi, Patrick. Are you all right? Using pip, I was able to install menpo, menpofit and menpodetect. However, in menpocli and menpo3d, I had problems with the freetype and png dependencies of matplotlib (as if they had not been installed). I tried using python 3.9, with python 2.7 and python 3.6, but the same thing happened. So, even using pip, I can't install on windows? Or is this problem related to something else?

**Comment by VictorFlavio123** [comment]
> 
> 
> > Yes windows isn't supported at the moment via conda. As I slowly remove all the Windows build requirements I may reenable this.
> 
> Hi, Patrick. Are you all right? Using pip, I was able to install menpo, menpofit and menpodetect. However, in menpocli and menpo3d, I had problems with the freetype and png dependencies of matplotlib (as if they had not been installed). I tried using python 3.9, with python 2.7 and python 3.6, but the same thing happened. So, even using pip, I can't install on windows? Or is this problem related to something else?

Sorry, about menpo3d is another problem (it's about conflict):

"The conflict is caused by:
     mayavi 4.7.2 depends on vtk
     mayavi 4.7.1 depends on vtk
     mayavi 4.7.0 depends on vtk "

**Comment by VictorFlavio123** [comment]
I was able to install everything using python 3.6! In fact, I reinstalled everything and it worked.
