### ISSUE TITLE
conda install -c menpo/channel/master -c conda-forge menpodetect=0.4.0  is not working

### ISSUE THREAD

**Issue by 92shehab** [menpo/menpo#855]
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Need some help to install menpodetect=0.4.0 . How can i install menpodetect=0.4.0  on python 3.5 version

**Comment by apapaion** [comment]
Have you tried conda install -c menpo menpodetect=0.4.0 ?

**Comment by 92shehab** [comment]
yes it says : 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - menpodetect=0.4.0 -> python=3.6

Your python: python=3.5

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

so what is the problem ?

**Comment by apapaion** [comment]
What's your menpo version? i have just created a new conda environment with python=3.5 (python 3.5.6 was installed) and installed menpo and menpodetect by using  conda install -c menpo menpo menpodetect=0.4.0

**Comment by 92shehab** [comment]
# packages in environment at /home/shehab/miniconda3/envs/menpo081:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.1                    openblas    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2018.8.24             py35_1001    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cyvlfeat                  0.4.6+2.g4594e91          py35_0    menpo/channel/master
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
dlib                      19.10           py35_blas_openblas_200  [blas_openblas]  conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
ffmpeg                    2.8.6                hf82bc7d_7    conda-forge
fontconfig                2.13.0               hd36ec8e_5    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gst-plugins-base          1.12.5            h3865690_1000    conda-forge
gstreamer                 1.12.5            h0cc0488_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
intel-openmp              2019.4                      243  
jpeg                      9d                   h36c2ea0_0    conda-forge
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.5.0               h14aa051_18    conda-forge
libgfortran4              7.5.0               h14aa051_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.34               ha92aebf_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.9             h648cc4a_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
matplotlib                2.1.2            py35h0e671d2_0  
menpo                     0.8.1+12.g2aea31e3  py35h2c751d1_0    menpo/channel/master
menpofit                  0.4.1+9.gf1b1515          py35_0    menpo/channel/master
mkl                       2018.0.3                      1  
ncurses                   6.2                  he6710b0_1  
numpy                     1.15.2          py35_blas_openblashd3ea46f_0  [blas_openblas]  conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2u               h516909a_0    conda-forge
pandas                    0.23.4           py35hf8a1672_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    4.3.0                    py35_2    conda-forge
pip                       10.0.1                   py35_0  
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.6.0            py35h8210e8a_7    conda-forge
python                    3.5.4               h417fded_24  
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
qt                        5.6.2               h974d657_12  
readline                  7.0                  h7b6447c_5  
scikit-learn              0.20.0          py35_blas_openblasha84fab4_201  [blas_openblas]  conda-forge
scipy                     0.19.1          py35_nomklh614202b_3  
setuptools                40.2.0                   py35_0  
sip                       4.18.1           py35hfc679d8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.20.1                        0    conda-forge
tk                        8.6.10               hbc83047_0  
tornado                   5.1.1            py35h470a237_0    conda-forge
vlfeat                    0.9.20            h14c3975_1002    conda-forge
wheel                     0.36.2             pyhd3eb1b0_0  
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  


package list

**Comment by 92shehab** [comment]
menpo 0.8.1+12.g2aea31e3 py35h2c751d1_0 menpo/channel/master

**Comment by apapaion** [comment]
I think one  issue here is the menpo version as I had to  downgrade to 0.7.7. You can try to downgrade it or you can create a new clean environment.

**Comment by 92shehab** [comment]
conda install -c menpo/channel/master -c conda-forge menpo=0.7.7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions


menpo0.7.7  conflicts ! in python 3.5  version

**Comment by patricksnape** [comment]
Please use conda-forge to install the packages - I cannot provide support for such old versions of menpo

conda install -c conda-forge menpo
