### ISSUE TITLE
ImportError: cannot import name 'hog' from 'menpo.feature' (/home/shehab/miniconda3/envs/menpo/lib/python3.9/site-packages/menpo/feature/__init__.py)

### ISSUE THREAD

**Issue by 92shehab** [menpo/menpo#856]
when i import hog using this code : 
from menpo.feature import hog, ndfeature 
it shows erros 

Errors :::
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-115181e46a02> in <module>
----> 1 from menpo.feature import hog, ndfeature # you can import no_op and dsift as well (hog is best for imfrared images though)
      2 IMAGE_PATH = "d:/downloads/FaceDB_PNG_2935" # "/home/temp/schock/Infrared/Databases/FaceDB_Snapshot"
      3 LANDMARK_GROUP = "LJSON" #or "PTS"
      4 # use hog or dsift if you want precision, no_op to save memory and speed (but no_op performs _really_ bad on thermal data)
      5 features = hog

ImportError: cannot import name 'hog' from 'menpo.feature' (/home/shehab/miniconda3/envs/menpo/lib/python3.9/site-packages/menpo/feature/__init__.py)

How can i solve it ?

**Comment by patricksnape** [comment]
Hog is no longer supported as a native feature. But you can always create your own feature functions and so you can recreate the old HOG features by using other packages and just defining a feature extraction function
