### ISSUE TITLE
ImportError: No module named 'cv2'

### ISSUE THREAD

**Issue by 92shehab** [menpo/menpo#857]
Environment list

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.1                    openblas    conda-forge
bleach                    3.3.0              pyhd3eb1b0_0  
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2021.1.19            h06a4308_0  
certifi                   2020.6.20          pyhd3eb1b0_3  
cycler                    0.10.0                     py_2    conda-forge
cyvlfeat                  0.4.6+2.g4594e91          py35_0    menpo/channel/master
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.4.2              pyhd3eb1b0_0  
defusedxml                0.7.0              pyhd3eb1b0_0  
dlib                      19.10           py35_blas_openblas_200  [blas_openblas]  conda-forge
entrypoints               0.2.3                    py35_2  
expat                     2.2.9                he1b5a44_2    conda-forge
ffmpeg                    2.8.6                hf82bc7d_7    conda-forge
fontconfig                2.13.0               hd36ec8e_5    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gst-plugins-base          1.12.5            h3865690_1000    conda-forge
gstreamer                 1.12.5            h0cc0488_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
intel-openmp              2019.4                      243  
ipykernel                 4.10.0                   py35_0  
ipython                   5.8.0                    py35_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.4.1                    py35_0  
jinja2                    2.11.3             pyhd3eb1b0_0  
joblib                    0.14.1                     py_0  
jpeg                      9d                   h36c2ea0_0    conda-forge
jsonschema                2.6.0            py35h4395190_0  
jupyter                   1.0.0                    py35_7  
jupyter_client            5.3.3                      py_0  
jupyter_console           5.2.0            py35h4044a63_1  
jupyter_core              4.5.0                      py_0  
kiwisolver                1.0.1            py35h2d50403_2    conda-forge
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.5.0               h14aa051_18    conda-forge
libgfortran4              7.5.0               h14aa051_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.34               ha92aebf_2    conda-forge
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.9             h648cc4a_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
markupsafe                1.0              py35h14c3975_1  
matplotlib                1.5.3                    pypi_0    pypi
menpo                     0.8.1+12.g2aea31e3  py35h2c751d1_0    menpo/channel/master
menpodetect               0.4.0                    pypi_0    pypi
menpofit                  0.4.1+9.gf1b1515          py35_0    menpo/channel/master
mistune                   0.8.3            py35h14c3975_1  
mkl                       2018.0.3                      1  
nbconvert                 5.5.0                      py_0  
nbformat                  5.1.2              pyhd3eb1b0_1  
ncurses                   6.2                  he6710b0_1  
notebook                  5.6.0                    py35_0  
numpy                     1.15.2          py35_blas_openblashd3ea46f_0  [blas_openblas]  conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openblas                  0.2.20                        8    conda-forge
opencv3                   3.1.0                    py35_0    <unknown>
openssl                   1.0.2u               h7b6447c_0  
packaging                 20.9               pyhd3eb1b0_0  
pandas                    0.23.4           py35hf8a1672_0    conda-forge
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.2                    py35_1  
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    4.3.0                    py35_2    conda-forge
pip                       10.0.1                   pypi_0    pypi
prometheus_client         0.9.0              pyhd3eb1b0_0  
prompt_toolkit            1.0.15           py35hc09de7a_0  
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2  
pygments                  2.8.0              pyhd3eb1b0_0  
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.6.0            py35h8210e8a_7    conda-forge
python                    3.5.4               h417fded_24  
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyzmq                     17.1.2           py35h14c3975_0  
qt                        5.6.2               h974d657_12  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  7.0                  h7b6447c_5  
scikit-learn              0.20.0          py35_blas_openblasha84fab4_201  [blas_openblas]  conda-forge
scipy                     0.19.1          py35_nomklh614202b_3  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                40.2.0                   py35_0  
simplegeneric             0.8.1                    py35_2  
sip                       4.18.1           py35hfc679d8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.20.1                        0    conda-forge
terminado                 0.8.1                    py35_1  
testpath                  0.4.4              pyhd3eb1b0_0  
tk                        8.6.10               hbc83047_0  
tornado                   5.1.1            py35h470a237_0    conda-forge
tqdm                      4.45.0                   pypi_0    pypi
traitlets                 4.3.2            py35ha522a97_0  
vlfeat                    0.9.20            h14c3975_1002    conda-forge
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py35_1  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.4.1                    py35_0  
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h7b6447c_0  
zeromq                    4.2.5                hf484d3e_1  
zlib                      1.2.11               h7b6447c_3  

**how to sole this issue ?**

**Comment by patricksnape** [comment]
Can't help debug environment issues - please install packages from only conda-forge
