### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var

### ISSUE THREAD

**Issue by 92shehab** [menpo/menpo#858]
#Envirnment List : 
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
boost                     1.59.0                   py35_0    menpo
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2021.1.19            h06a4308_1  
certifi                   2020.6.20          pyhd3eb1b0_3  
cycler                    0.10.0                     py_2    conda-forge
cyffld2                   0.2.4                    py35_0    menpo
cypico                    0.2.7                    py35_0    menpo
cyvlfeat                  0.4.6+2.g4594e91          py35_0    menpo/channel/master
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.4.2              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
dlib                      18.18                    py35_2    menpo
entrypoints               0.2.3                    py35_2  
expat                     2.2.9                he1b5a44_2    conda-forge
ffmpeg                    2.8.6                hf82bc7d_7    conda-forge
fftw                      3.3.9                h27cfd23_1  
fontconfig                2.13.0               hd36ec8e_5    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gst-plugins-base          1.12.5            h3865690_1000    conda-forge
gstreamer                 1.12.5            h0cc0488_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
imageio                   2.9.0                    pypi_0    pypi
intel-openmp              2019.4                      243  
ipykernel                 4.10.0                   py35_0  
ipython                   5.8.0                    py35_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                5.1.5                    py35_0    menpo
jinja2                    2.11.3             pyhd3eb1b0_0  
joblib                    0.10.3                   py35_0    menpo
jpeg                      9d                   h36c2ea0_0    conda-forge
jsonschema                2.6.0            py35h4395190_0  
jupyter                   1.0.0                    py35_7  
jupyter_client            5.3.3                      py_0  
jupyter_console           5.2.0            py35h4044a63_1  
jupyter_core              4.5.0                      py_0  
kiwisolver                1.0.1            py35h2d50403_2    conda-forge
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.5.0               h14aa051_18    conda-forge
libgfortran4              7.5.0               h14aa051_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.9             h648cc4a_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
markupsafe                1.0              py35h14c3975_1  
matplotlib                1.5.3                    pypi_0    pypi
menpo                     0.7.7                    pypi_0    pypi
menpodetect               0.5.0                    py35_0    menpo
menpofit                  0.4.1+9.gf1b1515          py35_0    menpo/channel/master
mistune                   0.8.3            py35h14c3975_1  
mkl                       2018.0.3                      1  
nbconvert                 5.5.0                      py_0  
nbformat                  5.1.2              pyhd3eb1b0_1  
ncurses                   6.2                  he6710b0_1  
networkx                  2.4                      pypi_0    pypi
notebook                  5.6.0                    py35_0  
numpy                     1.18.5                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv3                   3.1.0                    py35_0    menpo
openssl                   1.0.2u               h516909a_0    conda-forge
packaging                 20.9               pyhd3eb1b0_0  
pandas                    0.23.4           py35hf8a1672_0    conda-forge
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.2                    py35_1  
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    4.3.0                    pypi_0    pypi
pip                       10.0.1                   py35_0  
prometheus_client         0.9.0              pyhd3eb1b0_0  
prompt_toolkit            1.0.15           py35hc09de7a_0  
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2  
pygments                  2.8.0              pyhd3eb1b0_0  
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.6.0            py35h8210e8a_7    conda-forge
python                    3.5.6                hc3d631a_0  
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1                    pypi_0    pypi
pyzmq                     17.1.2           py35h14c3975_0  
qt                        5.6.2               hd25b39d_14  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  7.0                  h7b6447c_5  
scikit-image              0.15.0                   pypi_0    pypi
scikit-learn              0.20.0           py35h4989274_1  
scipy                     0.19.1                   pypi_0    pypi
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                40.2.0                   py35_0  
simplegeneric             0.8.1                    py35_2  
sip                       4.18.1           py35hfc679d8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h62c20be_0  
terminado                 0.8.1                    py35_1  
testpath                  0.4.4              pyhd3eb1b0_0  
tk                        8.6.10               hbc83047_0  
tornado                   5.1.1            py35h470a237_0    conda-forge
tqdm                      4.45.0                   pypi_0    pypi
traitlets                 4.3.2            py35ha522a97_0  
vlfeat                    0.9.20            h14c3975_1002    conda-forge
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py35_1  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        1.2.3                    py35_1    menpo
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h7b6447c_0  
zeromq                    4.2.5                hf484d3e_1  
zlib                      1.2.11               h7b6447c_3  

when i try to import cv2 it shows an error 
ImportError: /lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var

How to solve this issue ?

**Comment by patricksnape** [comment]
You have a very starnge environment involving packages from defualts, pip and conda-forge. I'm afraid I can't help debug this. Please create a new environment and only install packages from conda-forge.
