### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by 92shehab** [menpo/menpo#859]
This is my code : 

```
import cv2

# get points of bounding_box. left top and bottom right
p_left_top = fitting_result.final_shape.bounds()[0]
p_right_bottom = fitting_result.final_shape.bounds()[1]

image_width, image_height = test_img.width, test_img.height


# clip value to image range
p_left_top[0] = np.clip([p_left_top[0]], 0, image_height)[0]
p_left_top[1] = np.clip([p_left_top[1]], 0, image_width)[0]
p_right_bottom[0] = np.clip([p_right_bottom[0]], 0, image_height)[0]
p_right_bottom[1] = np.clip([p_right_bottom[1]], 0, image_width)[0]

#extract relevant image part
img_tmp = test_img.pixels.squeeze()[p_left_top[0]:p_right_bottom[0], p_left_top[1]:p_right_bottom[1]]*255

img_tmp = cv2.resize(img_tmp, (144, 144))

plt.imshow(img_tmp, cmap='gray')
plt.show()
```

![1](https://user-images.githubusercontent.com/35796580/110499139-271cc480-8122-11eb-897e-0e16c09fb44f.png)

i got an issue. How to solve ? Please help !

**Comment by patricksnape** [comment]
Can give more information about what you are trying to achieve?

Almost certainly the issue is that `np.clip` doesn't cast the value to integer and so it remains a float (which you cannot index with). So probably the fix is `test_img.pixels.squeeze()[int(p_left_top[0]):int(p_right_bottom[0]), int(p_left_top[1]):int(p_right_bottom[1])]*255`.

But if you just want to crop the image to the bounding box of the fitting results you can do that using menpo directly!

```
test_img.landmarks["final_result"] = fitting_result.final_shape
cropped_image = test_img.crop_to_landmarks(group="final_shape")
resized_image = cropped_image.resize((144, 144))
```

**Comment by 92shehab** [comment]
After getting fitting result i want to extract nose part only. How i can get the specific landmark part ? 
For example nose or eye or mouth etc ? 
![t](https://user-images.githubusercontent.com/35796580/111862543-2be24380-8980-11eb-86f2-5bc837a6ac1c.png)

Help me with source code.

**Comment by patricksnape** [comment]
I don't recognize that landmark set -> but it looks like it's already labelled. So you should be able to just pull the labels off?

Try something like:

```
pcloud = fitting_result.final_shape
print(pcloud.labels)
# One of the shapes should probably mention nose? Replace the "nose" label below with that label
pcloud.get_label("nose").view()
test_img.view()
```

**Comment by 92shehab** [comment]
Thank you for your replay.
![new](https://user-images.githubusercontent.com/35796580/111903351-19453880-8a6c-11eb-9b67-ea6d6a830af9.png)

My main goal is to extract mentioned part only and save as .png. How can i get the landmark points asis (x,y) values in nose label.

Help me with that.

**Comment by patricksnape** [comment]
Not sure what you mean again? You want to crop the image around those points and save the cropped image? Or save the landmarks for the nose?

From your code:

```
import menpo

# This saves the file
nose_pcloud = pcloud.get_label("centernose")
menpo.io.export_landmark_file(nose_pcloud, "/tmp/centernose.ljson", overwrite=True)

# If you just want access to the numpy array
nose_nparray = nose_pcloud.points

# If you want to crop the image to the nose region and save the image
cropped = image.crop_to_pointcloud(nose_pcloud)
menpo.io.export_image(cropped, "/tmp/cropped_image.png")
```

**Comment by 92shehab** [comment]
Thank you for you replay !
can you please share documentation link so that i can get the function list or sample code ? would be helpful !

**Comment by patricksnape** [comment]
Not sure what you want, the documentation for the api is on menpo.readthedocs.org
