### ISSUE TITLE
'appearance_reconstructions' returns matrices with weird size, values

### ISSUE THREAD

**Issue by LStandman** [menpo/menpo#867]
Hi,
I am having trouble reconstructing appearances with the pre-trained fitter.
According to the docs, _appearance_reconstructions_ should return a list of _menpo.image.Image_.
What I am getting is a list of matrices of size 68x1x8x13x13.

Even if I were to treat these items as a collection of 68 patches (this wouldn't match the docs AFAIK, but it might make sense for IBUG-68): Each patch would have 8 channels (8x13x13) rather than being RGB or greyscale . Furthermore, the cell values seem to be between 0-300 rather than 0-1.0.

See code below:
```
from menpofit.aam import load_balanced_frontal_face_fitter
from menpodetect import load_opencv_frontal_face_detector
import menpo.io as mio
import menpo

detector = load_opencv_frontal_face_detector()
fitter = load_balanced_frontal_face_fitter()
image = mio.import_image('test.jpg')
bboxes = detector(image)

if len(bboxes) < 1:
  print('face not  found')
  exit(-1)

result = fitter.fit_from_bb(image, bboxes[0], max_iters=20)
reconstructed = fitter.wrapped_fitter.appearance_reconstructions(result.appearance_parameters, result.n_iters_per_scale)[-1]

print(menpo.image.Image(reconstructed))
print(reconstructed)

exit(0)
```

Thank you in advance for your help and patience,
LS

**Comment by LStandman** [comment]
Hi,
I did some exploring, it seems to be a problem with all AAMs that are configured to use _menpo.feature.dsift_, _menpo.feature.fast_dsift_, etc.

Regards,
LS

**Comment by patricksnape** [comment]
The balanced frontal face fitter is indeed a patch based AAM that uses fast_dsift faetures. So the output is as expected.
