### ISSUE TITLE
Bug in edge_vectors() 

### ISSUE THREAD

**Issue by jacksoncsy** [menpo/menpo#868]
Hello guys, long time no see! 

I am not sure if menpo is still under maintenance. But I just found a bug in function edge_vectors() in:
https://github.com/menpo/menpo/blob/552b9a0484041064837ebb044e9a3f2f4b04e65d/menpo/shape/mesh/base.py

When the trilist number is odd, ".reshape(-1,2)" will give error. The corresponding function in 0.8.0 seems fine: https://github.com/menpo/menpo/blob/v0.8.0/menpo/shape/mesh/base.py

Many thanks, Shiyang

**Comment by patricksnape** [comment]
Thank for reporting! Fixed now in #871
