### ISSUE TITLE
Requesting a master release under 0.12.0

### ISSUE THREAD

**Issue by lucapericlp** [menpo/menpo#873]
Hey! I have a few legacy projects that depend on this project & we've reached the point where we're unable to make certain upgrades due to issues that were addressed in https://github.com/menpo/menpo/pull/862 but there hasn't been a master release since then.

I had a quick look at this project & it doesn't seem like I'd be able to contribute via PR to make this publish happen hence I've opened this issue with the hopes that a release is possible.

Thanks for the project & your time!

**Comment by patricksnape** [comment]
Better late than never....

https://github.com/menpo/menpo/releases/tag/v0.11.1
